---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-chat
  template:
    metadata:
      labels:
        app: backend-chat
    spec:
      containers:
      - name: backend-chat
        image: chris4929/yswchat:chat
        ports:
        - containerPort: 5000
